// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import com.google.gson.FieldNamingPolicy
import com.google.gson.GsonBuilder
import com.google.gson.reflect.TypeToken

object Sheet {
    private var isLoad = false
    private val gson = GsonBuilder().setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES).create()

    fun load(sheets: Map<String, String>) {
        load(StBitmapHolder, sheets["st_bitmap"])
        load(StConstantHolder, sheets["st_constant"])
        load(StI18nHolder, sheets["st_i18n"])
        load(StPropertyHolder, sheets["st_property"])
        load(StRankHolder, sheets["st_rank"])
        load(StRewardHolder, sheets["st_reward"])
        load(StRewardPoolHolder, sheets["st_reward_pool"])
        isLoad = true
    }

    fun check() {
        if (!isLoad) throw IllegalStateException("Sheet not loaded")
    }

    private fun <T> load(holder: SheetHolder<T>, json: String?) {
        holder.clear()
        if (json == null) return
        val values = gson.fromJson<Array<T>>(json, holder.type().arrayType())
        for (value in values) {
            holder.put(value)
        }
    }
}

interface SheetHolder<T> {
    fun put(value: T)
    fun clear()
    fun type(): Class<T>
}