// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

data class StBitmap(
    /** 配置id */
    val configId: String,
    /** 行数 */
    val row: Int,
    /** 列数 */
    val column: Int,
    /** 基线偏移 */
    val ascent: Int,
    /** 高度 */
    val height: Int,
    /** 图片高度 */
    val imgHeight: Int,
    /** 图片宽度 */
    val imgWidth: Int
)

fun Sheet.getAllStBitmap(): Map<String, StBitmap> {
    check()
    return StBitmapHolder.stBitmapMap
}

fun Sheet.getStBitmap(configId: String): StBitmap? {
    check()
    return StBitmapHolder.stBitmapMap[configId]
}

internal object StBitmapHolder : SheetHolder<StBitmap> {
    val stBitmapMap = mutableMapOf<String, StBitmap>()
    override fun put(value: StBitmap) {
        stBitmapMap[value.configId] = value
    }

    override fun clear() {
        stBitmapMap.clear()
    }
}