// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import java.util.Locale

data class StBitmap(
    /** 配置id */
    val configId: String,
    /** 字体 */
    val font: String,
    /** 行数 */
    val row: Int,
    /** 列数 */
    val column: Int,
    /** 基线偏移 */
    val ascent: Int,
    /** 高度 */
    val height: Int,
    /** 图片高度 */
    val imgHeight: Int,
    /** 图片宽度 */
    val imgWidth: Int
)

fun Sheet.getAllStBitmap(locale: Locale? = null): Map<String, StBitmap> {
    return holderStBitmap[locale].stBitmapMap
}

fun Sheet.getStBitmap(configId: String, locale: Locale? = null): StBitmap? {
    return holderStBitmap[locale].stBitmapMap[configId]
}

private class StBitmapFile {
    val stBitmapMap = mutableMapOf<String, StBitmap>()
}

private lateinit var holderStBitmap: SheetHolder<StBitmapFile>

internal fun loadStBitmap(tablePath: String) {
    val holder = SheetHolder<StBitmapFile>()
    holder.load<StBitmap>(tablePath, "st_rank") { elements ->
        StBitmapFile().apply {
            elements.forEach {
                stBitmapMap[it.configId] = it
            }
        }
    }
    holderStBitmap = holder
}