// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

private lateinit var stBitmapMap: Map<String, StBitmap>

data class StBitmap(
    /** 配置id */ 
    val configId: String,
    /** 字体 */ 
    val font: String,
    /** 行数 */ 
    val row: Int,
    /** 列数 */ 
    val column: Int,
    /** 基线偏移 */ 
    val ascent: Int,
    /** 高度 */ 
    val height: Int,
    /** 图片高度 */ 
    val imgHeight: Int,
    /** 图片宽度 */ 
    val imgWidth: Int
)

fun Sheet.getAllStBitmap(): Map<String, StBitmap> {
    return stBitmapMap
}

fun Sheet.getStBitmap(configId: String): StBitmap? {
    return stBitmapMap[configId]
}

internal fun loadStBitmap(gson: Gson, tablePath: String) {
    val jsonFile = File(tablePath, "st_bitmap.json")
    val jsonString = jsonFile.readText()
    val type = object : TypeToken<List<StBitmap>>() {}.type
    val list = gson.fromJson<List<StBitmap>>(jsonString, type)
    val map = mutableMapOf<String, StBitmap>()
    for (data in list) {
        map[data.configId] = data
    }
    stBitmapMap = map
}