// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

data class StConstant(
    /** 键名 */
    val key: String,
    /** 键值 */
    val value: String
)

fun Sheet.getAllStConstant(): Map<String, StConstant> {
    check()
    return holderStConstant.default.stConstantMap
}

fun Sheet.getStConstant(key: String): StConstant? {
    check()
    return holderStConstant.default.stConstantMap[key]
}

private class StConstantFile {
    val stConstantMap = mutableMapOf<String, StConstant>()
}

private lateinit var holderStConstant: SheetHolder<StConstantFile>

internal fun loadStConstant(tablePath: String) {
    val holder = SheetHolder<StConstantFile>()
    holder.load<StConstant>(tablePath, "st_constant") { elements ->
        StConstantFile().apply {
            elements.forEach {
                stConstantMap[it.key] = it
            }
        }
    }
    holderStConstant = holder
}