// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

data class StConstant(
    /** 键名 */
    val key: String,
    /** 键值 */
    val value: String
)

fun Sheet.getAllStConstant(): Map<String, StConstant> {
    check()
    return StConstantHolder.stConstantMap
}

fun Sheet.getStConstant(key: String): StConstant? {
    check()
    return StConstantHolder.stConstantMap[key]
}

internal object StConstantHolder : SheetHolder<StConstant> {
    val stConstantMap = mutableMapOf<String, StConstant>()
    override fun put(value: StConstant) {
        stConstantMap[value.key] = value
    }

    override fun clear() {
        stConstantMap.clear()
    }

    override fun type(): Class<StConstant> {
        return StConstant::class.java
    }
}