// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

data class StI18n(
    val key: String,
    val zhCn: String,
    val enUs: String,
    val jaJp: String
)

fun Sheet.getAllStI18n(): Map<String, StI18n> {
    check()
    return StI18nHolder.stI18nMap
}

fun Sheet.getStI18n(key: String): StI18n? {
    check()
    return StI18nHolder.stI18nMap[key]
}

internal object StI18nHolder : SheetHolder<StI18n> {
    val stI18nMap = mutableMapOf<String, StI18n>()
    override fun put(value: StI18n) {
        stI18nMap[value.key] = value
    }

    override fun clear() {
        stI18nMap.clear()
    }
}