// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

private lateinit var stMessageMap: Map<String, StMessage>

data class StMessage(
    /** 键名 */ 
    val key: String,
    /** 键值 */ 
    val value: String
)

fun Sheet.getAllStMessage(): Map<String, StMessage> {
    return stMessageMap
}

fun Sheet.getStMessage(key: String): StMessage? {
    return stMessageMap[key]
}

internal fun loadStMessage(gson: Gson, tablePath: String) {
    val jsonFile = File(tablePath, "st_message.json")
    val jsonString = jsonFile.readText()
    val type = object : TypeToken<List<StMessage>>() {}.type
    val list = gson.fromJson<List<StMessage>>(jsonString, type)
    val map = mutableMapOf<String, StMessage>()
    for (data in list) {
        map[data.key] = data
    }
    stMessageMap = map
}