// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import java.util.Locale

data class StMessage(
    /** 键名 */
    val key: String,
    /** 键值 */
    val value: String
)

fun Sheet.getAllStMessage(locale: Locale? = null): Map<String, StMessage> {
    check()
    return holderStMessage[locale].stMessageMap
}

fun Sheet.getStMessage(key: String, locale: Locale? = null): StMessage? {
    check()
    return holderStMessage[locale].stMessageMap[key]
}

private class StMessageFile {
    val stMessageMap = mutableMapOf<String, StMessage>()
}

private lateinit var holderStMessage: SheetHolder<StMessageFile>

internal fun loadStMessage(tablePath: String) {
    val holder = SheetHolder<StMessageFile>()
    holder.load<StMessage>(tablePath, "st_message") { elements ->
        StMessageFile().apply {
            elements.forEach {
                stMessageMap[it.key] = it
            }
        }
    }
    holderStMessage = holder
}