// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

data class StMessage(
    /** 键名 */
    val key: String,
    /** 键值 */
    val value: String
)

fun Sheet.getAllStMessage(): Map<String, StMessage> {
    check()
    return StMessageHolder.stMessageMap
}

fun Sheet.getStMessage(key: String): StMessage? {
    check()
    return StMessageHolder.stMessageMap[key]
}

internal object StMessageHolder : SheetHolder<StMessage> {
    val stMessageMap = mutableMapOf<String, StMessage>()
    override fun put(value: StMessage) {
        stMessageMap[value.key] = value
    }

    override fun clear() {
        stMessageMap.clear()
    }
}