// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import java.util.Locale

data class StProperty(
    /** 配置id */
    val configId: Int,
    /** 名称 */
    val name: String
)

fun Sheet.getAllStProperty(locale: Locale? = null): Map<Int, StProperty> {
    check()
    return holderStProperty[locale].stPropertyMap
}

fun Sheet.getStProperty(configId: Int, locale: Locale? = null): StProperty? {
    check()
    return holderStProperty[locale].stPropertyMap[configId]
}

private class StPropertyFile {
    val stPropertyMap = mutableMapOf<Int, StProperty>()
}

private lateinit var holderStProperty: SheetHolder<StPropertyFile>

internal fun loadStProperty(tablePath: String) {
    val holder = SheetHolder<StPropertyFile>()
    holder.load<StProperty>(tablePath, "st_property") { elements ->
        StPropertyFile().apply {
            elements.forEach {
                stPropertyMap[it.configId] = it
            }
        }
    }
    holderStProperty = holder
}