// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

data class StProperty(
    /** 配置id */
    val configId: Int,
    /** 名称 */
    val name: String
)

fun Sheet.getAllStProperty(): Map<Int, StProperty> {
    check()
    return StPropertyHolder.stPropertyMap
}

fun Sheet.getStProperty(configId: Int): StProperty? {
    check()
    return StPropertyHolder.stPropertyMap[configId]
}

internal object StPropertyHolder : SheetHolder<StProperty> {
    val stPropertyMap = mutableMapOf<Int, StProperty>()
    override fun put(value: StProperty) {
        stPropertyMap[value.configId] = value
    }

    override fun clear() {
        stPropertyMap.clear()
    }
}