// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

private lateinit var stPropertyMap: Map<Int, StProperty>

data class StProperty(
    /** 配置id */ 
    val configId: Int,
    /** 名称 */ 
    val name: String
)

fun Sheet.getAllStProperty(): Map<Int, StProperty> {
    return stPropertyMap
}

fun Sheet.getStProperty(configId: Int): StProperty? {
    return stPropertyMap[configId]
}

internal fun loadStProperty(gson: Gson, tablePath: String) {
    val jsonFile = File(tablePath, "st_property.json")
    val jsonString = jsonFile.readText()
    val type = object : TypeToken<List<StProperty>>() {}.type
    val list = gson.fromJson<List<StProperty>>(jsonString, type)
    val map = mutableMapOf<Int, StProperty>()
    for (data in list) {
        map[data.configId] = data
    }
    stPropertyMap = map
}