// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

lateinit var stRankMap: Map<Int/* configId */, StRank>
    private set

data class StRank(
    /** 配置id */ 
    val configId: Int,
    /** 名称 */ 
    val name: String,
    /** 聊天名字颜色 */ 
    val nameColor: String,
    /** 聊天文本颜色 */ 
    val chatColor: String,
)

internal fun loadStRank(gson: Gson, tablePath: String) {
    val jsonFile = File(tablePath, "st_rank.json")
    val jsonString = jsonFile.readText()
    val type = object : TypeToken<List<StRank>>() {}.type
    val list = gson.fromJson<List<StRank>>(jsonString, type)
    val map = mutableMapOf<Int, StRank>()
    for (data in list) {
        map[data.configId] = data
    }
    stRankMap = map
}