// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import java.util.*

data class StRank(
    /** 配置id */
    val configId: Int,
    /** 名称 */
    val name: String,
    /** 聊天名字颜色 */
    val nameColor: String,
    /** 聊天文本颜色 */
    val chatColor: String
)

fun Sheet.getAllStRank(locale: Locale? = null): Map<Int, StRank> {
    check()
    return holderStRank[locale].stRankMap
}

fun Sheet.getStRank(configId: Int, locale: Locale? = null): StRank? {
    check()
    return holderStRank[locale].stRankMap[configId]
}

private class StRankFile {
    val stRankMap = mutableMapOf<Int, StRank>()
}

private lateinit var holderStRank: SheetHolder<StRankFile>

internal fun loadStRank(tablePath: String) {
    val holder = SheetHolder<StRankFile>()
    holder.load<StRank>(tablePath, "st_rank") { elements ->
        StRankFile().apply {
            elements.forEach {
                stRankMap[it.configId] = it
            }
        }
    }
    holderStRank = holder
}