// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

data class StRewardPool(
    /** 配置id */
    val poolId: Int,
    /** 类型 */
    val type: Int,
    /** 物品id */
    val id: Int,
    /** 数量 */
    val amount: Int,
    /** 权重 */
    val weight: Int
)

fun Sheet.getStRewardPools(poolId: Int): List<StRewardPool> {
    check()
    return StRewardPoolHolder.stRewardPoolAMap[poolId] ?: emptyList()
}

internal object StRewardPoolHolder : SheetHolder<StRewardPool> {
    val stRewardPoolAMap = mutableMapOf<Int, MutableList<StRewardPool>>()
    override fun put(value: StRewardPool) {
        stRewardPoolAMap.getOrPut(value.poolId) { mutableListOf() }.add(value)
    }

    override fun clear() {
        stRewardPoolAMap.clear()
    }

    override fun type(): Class<StRewardPool> {
        return StRewardPool::class.java
    }
}