// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

data class StRewardPool(
    /** 配置id */
    val poolId: Int,
    /** 类型 */
    val type: Int,
    /** 物品id */
    val id: Int,
    /** 数量 */
    val amount: Int,
    /** 权重 */
    val weight: Int
)

fun Sheet.getStRewardPool(poolId: Int, index: Int): List<StRewardPool> {
    check()
    return holderStRewardPool.default.stRewardPoolAMap[poolId] ?: emptyList()
}

fun Sheet.getStRewardPools(poolId: Int): List<StRewardPool> {
    check()
    return holderStRewardPool.default.stRewardPoolAMap[poolId] ?: emptyList()
}

private class StRewardPoolFile {
    val stRewardPoolAMap = mutableMapOf<Int, MutableList<StRewardPool>>()
}

private lateinit var holderStRewardPool: SheetHolder<StRewardPoolFile>

internal fun loadStRewardPool(tablePath: String) {
    val holder = SheetHolder<StRewardPoolFile>()
    holder.load<StRewardPool>(tablePath, "st_reward_pool") { elements ->
        StRewardPoolFile().apply {
            elements.forEach {
                stRewardPoolAMap.getOrPut(it.poolId) { mutableListOf() }.add(it)
            }
        }
    }
    holderStRewardPool = holder
}