// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

private lateinit var stRewardPoolAMap: Map<Int, List<StRewardPool>>

data class StRewardPool(
    /** 配置id */ 
    val poolId: Int,
    /** 类型 */ 
    val type: Int,
    /** 物品id */ 
    val id: Int,
    /** 数量 */ 
    val amount: Int,
    /** 权重 */ 
    val weight: Int
)

fun Sheet.getStRewardPool(poolId: Int, index: Int): List<StRewardPool> {
    return stRewardPoolAMap[poolId] ?: emptyList()
}

fun Sheet.getStRewardPools(poolId: Int): List<StRewardPool> {
    return stRewardPoolAMap[poolId] ?: emptyList()
}

internal fun loadStRewardPool(gson: Gson, tablePath: String) {
    val jsonFile = File(tablePath, "st_reward_pool.json")
    val jsonString = jsonFile.readText()
    val type = object : TypeToken<List<StRewardPool>>() {}.type
    val list = gson.fromJson<List<StRewardPool>>(jsonString, type)
    val aMap = mutableMapOf<Int, MutableList<StRewardPool>>()
    for (data in list) {
        aMap.getOrPut(data.poolId) { mutableListOf() }.add(data)
    }
    stRewardPoolAMap = aMap
}