// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

import java.util.Locale

data class StReward(
    /** 配置id */
    val rewardId: Int,
    /** 类型 */
    val type: Int,
    /** 物品id */
    val id: Int,
    /** 数量 */
    val amount: Int
)

fun Sheet.getStReward(rewardId: Int, index: Int, locale: Locale? = null): List<StReward> {
    check()
    return holderStReward[locale].stRewardAMap[rewardId] ?: emptyList()
}

fun Sheet.getStRewards(rewardId: Int, locale: Locale? = null): List<StReward> {
    check()
    return holderStReward[locale].stRewardAMap[rewardId] ?: emptyList()
}

private class StRewardFile {
    val stRewardAMap = mutableMapOf<Int, MutableList<StReward>>()
}

private lateinit var holderStReward: SheetHolder<StRewardFile>

internal fun loadStReward(tablePath: String) {
    val holder = SheetHolder<StRewardFile>()
    holder.load<StReward>(tablePath, "st_rank") { elements ->
        StRewardFile().apply {
            elements.forEach {
                stRewardAMap.getOrPut(it.rewardId) { mutableListOf() }.add(it)
            }
        }
    }
    holderStReward = holder
}