// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package server.common.sheet

data class StReward(
    /** 配置id */
    val rewardId: Int,
    /** 类型 */
    val type: Int,
    /** 物品id */
    val id: Int,
    /** 数量 */
    val amount: Int
)

fun Sheet.getStRewards(rewardId: Int): List<StReward> {
    check()
    return StRewardHolder.stRewardAMap[rewardId] ?: emptyList()
}

internal object StRewardHolder : SheetHolder<StReward> {
    val stRewardAMap = mutableMapOf<Int, MutableList<StReward>>()
    override fun put(value: StReward) {
        stRewardAMap.getOrPut(value.rewardId) { mutableListOf() }.add(value)
    }

    override fun clear() {
        stRewardAMap.clear()
    }
}