// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package top.nipuru.prushka.common.sheet

import com.google.gson.FieldNamingPolicy
import com.google.gson.GsonBuilder

object Sheet {
    fun load(tablePath: String) {
        val gson = GsonBuilder().setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES).create()
        loadStBitmap(gson, tablePath)
        loadStBitmap(gson, tablePath)
        loadStConstant(gson, tablePath)
        loadStMessage(gson, tablePath)
        loadStProperty(gson, tablePath)
        loadStRank(gson, tablePath)
        loadStReward(gson, tablePath)
        loadStRewardPool(gson, tablePath)
    }
}