// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package top.nipuru.prushka.common.sheet

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

lateinit var stConstantMap: Map<String/* key */, StConstant>
    private set

data class StConstant(
    /** 键名 */ 
    val key: String,
    /** 键值 */ 
    val value: String
)

internal fun loadStConstant(gson: Gson, tablePath: String) {
    val jsonFile = File(tablePath, "st_constant.json")
    val jsonString = jsonFile.readText()
    val type = object : TypeToken<List<StConstant>>() {}.type
    val list = gson.fromJson<List<StConstant>>(jsonString, type)
    val map = mutableMapOf<String, StConstant>()
    for (data in list) {
        map[data.key] = data
    }
    stConstantMap = map
}