// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package top.nipuru.prushka.server.common.sheet

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

lateinit var stPropertyMap: Map<Int/* configId */, StProperty>
    private set

data class StProperty(
    /** 配置id */ 
    val configId: Int,
    /** 名称 */ 
    val name: String
)

internal fun loadStProperty(gson: Gson, tablePath: String) {
    val jsonFile = File(tablePath, "st_property.json")
    val jsonString = jsonFile.readText()
    val type = object : TypeToken<List<StProperty>>() {}.type
    val list = gson.fromJson<List<StProperty>>(jsonString, type)
    val map = mutableMapOf<Int, StProperty>()
    for (data in list) {
        map[data.configId] = data
    }
    stPropertyMap = map
}