// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package top.nipuru.prushka.server.common.sheet

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

lateinit var stRewardPoolAMap: Map<Int/* poolId */, List<top.nipuru.prushka.server.common.sheet.StRewardPool>>
    private set

data class StRewardPool(
    /** 配置id */ 
    val poolId: Int,
    /** 类型 */ 
    val type: Int,
    /** 物品id */ 
    val id: Int,
    /** 数量 */
    val num: Int,
    /** 权重 */ 
    val weight: Int
)

internal fun loadStRewardPool(gson: Gson, tablePath: String) {
    val jsonFile = File(tablePath, "st_reward_pool.json")
    val jsonString = jsonFile.readText()
    val type = object : TypeToken<List<top.nipuru.prushka.server.common.sheet.StRewardPool>>() {}.type
    val list = gson.fromJson<List<top.nipuru.prushka.server.common.sheet.StRewardPool>>(jsonString, type)
    val aMap = mutableMapOf<Int, MutableList<top.nipuru.prushka.server.common.sheet.StRewardPool>>()
    for (data in list) {
        aMap.getOrPut(data.poolId) { mutableListOf() }.add(data)
    }
    top.nipuru.prushka.server.common.sheet.stRewardPoolAMap = aMap
}