// This file is auto-generated. DO NOT EDIT.
// Generated by tool
package top.nipuru.prushka.common.sheet

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

lateinit var stMessageMap: Map<String/* key */, StMessage>
    private set

data class StMessage(
    /** 键名 */ 
    val key: String,
    /** 键值 */ 
    val value: String
)

internal fun loadStMessage(gson: Gson, tablePath: String) {
    val jsonFile = File(tablePath, "st_message.json")
    val jsonString = jsonFile.readText()
    val type = object : TypeToken<List<StMessage>>() {}.type
    val list = gson.fromJson<List<StMessage>>(jsonString, type)
    val map = mutableMapOf<String, StMessage>()
    for (data in list) {
        map[data.key] = data
    }
    stMessageMap = map
}