name: Prushka
version: 'dev'
api-version: "1.21"
dependencies:
  server:
    AfyBroker:
      load: BEFORE
      required: true
main: server.bukkit.BukkitPlugin
bootstrapper: server.bukkit.BukkitBootstrap
authors: [ Nipuru ]
load: STARTUP